name: Run Cypress in chrome
on: [push]
jobs:
  functionalTests:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node14.15.0-chrome86-ff82
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: |
            cypress/integration/functionalTests/login.spec.js
            cypress/integration/functionalTests/mockSignup.spec.js

  visualTests:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node14.15.0-chrome86-ff82
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        run: |
          npm run cy-update
          npm run cy-visual

